application:
  messaging:
    input-queue: RECEPCION.SOLICITUDES.MIAM
    input-report-queue: RECEPCION.REPORTES.MIAM
spring:
  batch:
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  application:
    name: mian-edge-api
  datasource:
    url: ${DB_URL}
    driverClassName: 'org.postgresql.Driver'
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ibm:
    mq:
      host: ${MQ_HOST}
      port: ${MQ_PORT}
      queue-manager: ${MQ_QUEUE_MANAGER}
      channel: ${MQ_CHANNEL}
      username: ${MQ_USER}
      password: ${MQ_PASSWORD}
      receive-timeout: 2000
  config:
    import: env.properties
server:
  port: 8081

app:
  jwt-secret: ${JWT_KEY}
  jwt-expiration-min: 43200
  onesignal-app-id: ${ONESIGNAL_APP_ID}
  onesignal-api-key: ${ONESIGNAL_API_KEY}
  onesignal-api-url: ${ONESIGNAL_API_URL}