application:
  messaging:
    input-queue: RECEPCION.SOLICITUDES.MIAM
    input-report-queue: RECEPCION.REPORTES.MIAM
spring:
  batch:
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  application:
    name: mian-edge-api
  datasource:
    url: jdbc:mysql://localhost:3306/miam_edge_api?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driverClassName: 'com.mysql.cj.jdbc.Driver'
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ibm:
    mq:
      host: localhost
      port: 1000
      queue-manager: QMORDENES
      channel: DEV.APP.SVRCONN
      username: app
      password: app
      receive-timeout: 2000